Question1

In [1]:
import numpy as np
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1)
list1 = array1.tolist()
print(list1)

[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


Question2

In [2]:
import numpy as np
array2 = np.array([[5,7,9],[3,2,1],[6,5,1]])
trace = np.trace(array2) #5+3+1=8
print("the sum of the diagonal elements of the array is ",trace)

the sum of the diagonal elements of the array is  8


Question3

In [3]:
import numpy as np
array3 = np.array([[1,2],[3,5]])
x=int(input("Enter the value of x "))
print("Values bigger than x =", array3[array3>x])

Enter the value of x 2
Values bigger than x = [3 5]


Question4

In [4]:
import numpy as np
A = np.array([[5,10,12],[15,2,3]])
B = np.array([[3,2,1],[1,4,7]])
C = ([])
k =0
for i in A:
    j = i + B[k]
    C.append(j)
    k == k+1
print(C)

[array([ 8, 12, 13]), array([18,  4,  4])]


Question5

In [5]:
import numpy as np
A=np.array([[3,5],[9,10],[12,5]])
B=np.mean (A, axis=1)
print(B)

[4.  9.5 8.5]
